"""initial_schema

Revision ID: 6b1e3cccdf95
Revises: 
Create Date: 2026-08-14 11:29:05.381643
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6b1e3cccdf95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_uuid'), 'organizations', ['uuid'], unique=True)
    op.create_table('encryption_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('key_type', sa.Enum('ECC', 'AES', name='keytype'), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ROTATED', 'REVOKED', name='keystatus'), nullable=False),
    sa.Column('public_key_hex', sa.Text(), nullable=True),
    sa.Column('encrypted_private_key', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_key_material', sa.LargeBinary(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('rotation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rotated_from_id'], ['encryption_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encryption_keys_uuid'), 'encryption_keys', ['uuid'], unique=True)
    op.create_index('ix_keys_org_id', 'encryption_keys', ['organization_id'], unique=False)
    op.create_index('ix_keys_status', 'encryption_keys', ['status'], unique=False)
    op.create_table('storage_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.Enum('LOCAL', 'AWS_S3', 'AZURE_BLOB', name='storageprovidertype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('encrypted_config', sa.LargeBinary(), nullable=True),
    sa.Column('display_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_configs_uuid'), 'storage_configs', ['uuid'], unique=True)
    op.create_index('ix_storage_org_id', 'storage_configs', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email'),
    sa.UniqueConstraint('organization_id', 'username', name='uq_user_org_username')
    )
    op.create_index('ix_users_org_id', 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=True),
    sa.Column('allowed_origins', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('storage_provider_id', sa.Integer(), nullable=True),
    sa.Column('encryption_policy', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_provider_id'], ['storage_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_client_id'), 'applications', ['client_id'], unique=True)
    op.create_index('ix_applications_org_id', 'applications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_applications_uuid'), 'applications', ['uuid'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_created', 'api_usage', ['created_at'], unique=False)
    op.create_index('ix_usage_org_id', 'api_usage', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('USER_LOGIN', 'USER_REGISTER', 'APPLICATION_CREATED', 'APPLICATION_REVOKED', 'KEY_CREATED', 'KEY_ROTATED', 'KEY_REVOKED', 'FILE_ENCRYPTED', 'FILE_DECRYPTED', 'FILE_DELETED', 'STORAGE_CONNECTED', 'AUTHENTICATION_FAILED', 'AUTHORIZATION_FAILED', 'SECRET_ROTATED', name='auditeventtype'), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_org_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_table('encrypted_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('encrypted_size', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Enum('STANDARD_AES', 'HYBRID_AES_ECC', 'CHUNKED_AES', name='encryptionstrategyenum'), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('key_wrap', sa.String(length=50), nullable=True),
    sa.Column('encryption_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('storage_provider_type', sa.Enum('LOCAL', 'AWS_S3', 'AZURE_BLOB', name='storageprovidertype'), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('encryption_key_id', sa.Integer(), nullable=True),
    sa.Column('is_chunked', sa.Boolean(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['encryption_key_id'], ['encryption_keys.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_files_uuid'), 'encrypted_files', ['uuid'], unique=True)
    op.create_index('ix_files_app_id', 'encrypted_files', ['application_id'], unique=False)
    op.create_index('ix_files_org_id', 'encrypted_files', ['organization_id'], unique=False)
    op.create_index('ix_files_user_id', 'encrypted_files', ['user_id'], unique=False)
    op.create_table('encryption_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.Enum('STANDARD_AES', 'HYBRID_AES_ECC', 'CHUNKED_AES', name='encryptionstrategyenum'), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['encrypted_files.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encryption_operations_request_id'), 'encryption_operations', ['request_id'], unique=False)
    op.create_index(op.f('ix_encryption_operations_uuid'), 'encryption_operations', ['uuid'], unique=True)
    op.create_index('ix_operations_created', 'encryption_operations', ['created_at'], unique=False)
    op.create_index('ix_operations_org_id', 'encryption_operations', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operations_org_id', table_name='encryption_operations')
    op.drop_index('ix_operations_created', table_name='encryption_operations')
    op.drop_index(op.f('ix_encryption_operations_uuid'), table_name='encryption_operations')
    op.drop_index(op.f('ix_encryption_operations_request_id'), table_name='encryption_operations')
    op.drop_table('encryption_operations')
    op.drop_index('ix_files_user_id', table_name='encrypted_files')
    op.drop_index('ix_files_org_id', table_name='encrypted_files')
    op.drop_index('ix_files_app_id', table_name='encrypted_files')
    op.drop_index(op.f('ix_encrypted_files_uuid'), table_name='encrypted_files')
    op.drop_table('encrypted_files')
    op.drop_index('ix_audit_org_id', table_name='audit_logs')
    op.drop_index('ix_audit_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_usage_org_id', table_name='api_usage')
    op.drop_index('ix_usage_created', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_applications_uuid'), table_name='applications')
    op.drop_index('ix_applications_org_id', table_name='applications')
    op.drop_index(op.f('ix_applications_client_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index('ix_users_org_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_storage_org_id', table_name='storage_configs')
    op.drop_index(op.f('ix_storage_configs_uuid'), table_name='storage_configs')
    op.drop_table('storage_configs')
    op.drop_index('ix_keys_status', table_name='encryption_keys')
    op.drop_index('ix_keys_org_id', table_name='encryption_keys')
    op.drop_index(op.f('ix_encryption_keys_uuid'), table_name='encryption_keys')
    op.drop_table('encryption_keys')
    op.drop_index(op.f('ix_organizations_uuid'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
