"""description of the changes

Revision ID: 0007
Revises: 0006
Create Date: 2025-04-01 00:17:27.371093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecc_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_guid', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(length=1024), nullable=False),
    sa.Column('private_key', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_guid'], ['chat.user.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_guid'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_ecc_keys_id'), 'ecc_keys', ['id'], unique=False, schema='chat')
    op.create_table('encrypted_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('user_guid', sa.UUID(), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_guid'], ['chat.user.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_encrypted_files_id'), 'encrypted_files', ['id'], unique=False, schema='chat')
    op.add_column('message', sa.Column('ecc_key_id', sa.UUID(), nullable=True), schema='chat')
    op.create_foreign_key(None, 'message', 'ecc_keys', ['ecc_key_id'], ['id'], source_schema='chat', referent_schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', schema='chat', type_='foreignkey')
    op.drop_column('message', 'ecc_key_id', schema='chat')
    op.drop_index(op.f('ix_chat_encrypted_files_id'), table_name='encrypted_files', schema='chat')
    op.drop_table('encrypted_files', schema='chat')
    op.drop_index(op.f('ix_chat_ecc_keys_id'), table_name='ecc_keys', schema='chat')
    op.drop_table('ecc_keys', schema='chat')
    # ### end Alembic commands ###
